name: Run tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      shell: bash
      run: |
        python -m pip install --upgrade setuptools wheel pip
        pip install fugashi[unidic-lite] jaconv
        pip install .
    - name: Run tests
      run: |
        pytest cutlet/test

