name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - name: Install deps
      shell: bash
      run: |
        python -m pip install --upgrade setuptools wheel pip
        pip install fugashi[unidic-lite] jaconv pytest
    - name: Run tests
      run: |
        pytest

