name: Run tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      shell: bash
      run: |
        python3 -m pip install --upgrade setuptools wheel pip pytest 
        pip3 install fugashi[unidic-lite] jaconv
    - name: Run tests
      run: |
        pytest cutlet/test

